/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jose.ranieri (https://sketchfab.com/jose.ranieri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adult-dragon-b1667e01947148e5bea733b3b69cdccc
Title: Adult Dragon
*/

import { GroupProps } from "@react-three/fiber";
import { useContactDragon } from "../model";

type Props = GroupProps & {
  animationSpeed?: number;
};

export function ContactDragon({ animationSpeed = 1, ...props }: Props) {
  const { group, nodes, materials } = useContactDragon(animationSpeed);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group scale={0.258} name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Lamp"
              scale={2.644}
              rotation={[-0.268, 0.602, 1.932]}
              position={[15.333, 12.533, 17.243]}
            >
              <group name="Lamp_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp001"
              rotation={[-0.268, 0.602, 1.932]}
              position={[-15.333, 12.533, 17.243]}
            >
              <group name="Lamp001_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp002"
              rotation={[-0.268, 0.602, 1.932]}
              position={[-15.333, -12.342, 17.243]}
            >
              <group name="Lamp002_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp003"
              rotation={[-0.268, 0.602, 1.932]}
              position={[15.333, -12.342, 17.243]}
            >
              <group name="Lamp003_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp004"
              rotation={[-0.268, 0.602, 1.932]}
              position={[15.333, -12.342, -12.763]}
            >
              <group name="Lamp004_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp005"
              rotation={[-0.268, 0.602, 1.932]}
              position={[-15.333, -12.342, -12.763]}
            >
              <group name="Lamp005_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp006"
              rotation={[-0.268, 0.602, 1.932]}
              position={[-15.333, 12.533, -12.763]}
            >
              <group name="Lamp006_1" />
            </group>
            <group
              scale={2.644}
              name="Lamp007"
              rotation={[-0.268, 0.602, 1.932]}
              position={[15.333, 12.533, -12.763]}
            >
              <group name="Lamp007_1" />
            </group>
            <group name="Ossos" position={[0, 0.041, -0.015]}>
              <primitive object={nodes.Ossos_rootJoint} />
              <skinnedMesh
                name="Cube_0"
                material={materials.Material}
                geometry={nodes.Cube_0.geometry}
                skeleton={nodes.Cube_0.skeleton}
              />
              <group name="Cube" scale={0.507} position={[0, -0.063, 1.194]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
